name: Build and Publish Singularity Image

on:
  push:
    tags:
      - 'v*.*.*'    # Por ejemplo, cuando hagas un release o tag con formato v1.0.0
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # 2. Install a specific Singularity version using setup-singularity
      - name: Setup Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
      
      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # remove 'refs/tags/' prefix and store as VERSION
          echo "VERSION=${GITHUB_REF_NAME#refs/tags/}" >> $GITHUB_ENV

      - name: Inject version into .def
        run: |
          # Suppose your .def file has a line: VERSION "1.0"
          # We'll replace it with the real version from $VERSION
           sed -i "s/PLACEHOLDER_VERSION/${VERSION}/g" Singularity.def
      
      - name: Build SIF
        run: |
          sudo -E /opt/hostedtoolcache/singularity/3.8.3/x64/bin/singularity build omicverse_custom.sif Singularity.def

      - name: Minimal Test
        run: |
          # Ejemplo sencillo: verificar importación de torch
          sudo -E /opt/hostedtoolcache/singularity/3.8.3/x64/bin/singularity exec omicverse_custom.sif python -c "import torch; print(torch.__version__)"
          sudo -E /opt/hostedtoolcache/singularity/3.8.3/x64/bin/singularity exec omicverse_custom.sif python -c "import omicverse; print(omicverse.__version__)"
      - name: End
        run: | 
          echo Test run successully!
